model:
    name: ImageClassifier
    args:
        n_classes: 8
        parent: resnext50_32x4d    # torchvision.models.<this>
        dropout: 0.3
        intermediate: 64
optimizer:
    name: Adam
    args:
        lr: 0.0005
        betas: [0.9, 0.999]

scheduler:
    name: inverse_sqrt
    args:
        peak_lr: 0.0005
        warmup: 2000

train:
    data: ../data/hirise/train
    batch_size: 50
    max_step: 400_000
    max_epoch: 200
    checkpoint: 1000

validation:
    data: ../data/hirise/val
    batch_size: 100
    patience: 10
    by: macro_f1
    keep: 10                # keep these many models

tests:
   test:
      data: ../data/hirise/val




