model:
    name: ImageClassifier
    args:
        n_classes: 19
        parent: inception_v3    # torchvision.models.<this>
        intermediate: 64
        dropout: 0.3

optimizer:
    name: Adam
    args:
        lr: 0.005
        betas: [0.9, 0.999]

scheduler:
    name: inverse_sqrt
    args:
        peak_lr: 0.0005
        warmup: 2000

train:
    data: ../data/msl/train
    batch_size: 15
    max_step: 300_000
    max_epoch: 200
    # checkpoint: 1_000
    checkpoint: 250

validation:
    data: ../data/msl/val
    batch_size: 100
    patience: 20
    by: macro_f1
    keep: 10                # keep these many models




