model:
    name: ImageClassifier
    args:
        n_classes: 8
        parent: resnext50_32x4d    # torchvision.models.<this>
        dropout: 0.3
        intermediate: 24
optimizer:
    name: Adam
    args:
        lr: 0.0005
        betas: [0.9, 0.999]

scheduler:
    name: inverse_sqrt
    args:
        peak_lr: 0.00001
        warmup: 1000

train:
    data: ../data/hirise/train
    batch_size: 50
    max_step: 100_000
    max_epoch: 100
    checkpoint: 500

validation:
    data: ../data/hirise/val
    batch_size: 100
    patience: 10
    by: macro_f1
    keep: 10                # keep these many models





